---
title: Ordering Context
---

classDiagram
    class Customer {
        <<Entity>>
        -CustomerId id
        -FullName fullName
        -BirthDate birthDate
        -Email email
        -Phone phone
        -Document document
        -Boolean promotionNotificationsAllowed
        -Boolean archived
        -Instant registeredAt
        -Instant archivedAt
        -LoyaltyPoints loyaltyPoints
        +addLoyaltyPoints(LoyaltyPoints loyaltyPointsToAdd) void
        +archive() void
        +enablePromotionNotifications() void
        +disablePromotionNotifications() void
        +changeName(FullName newName) void
        +changeEmail(Email newEmail) void
        +changePhone(Phone newPhone) void
        +changeAddress(Address newAddress)
    }
    class Address {
        <<ValueObject>>
        -String street
        -String number
        -String complement
        -String neighborhood
        -String city
        -String state
        -ZipCode zipCode
    }
    Address <--* Customer: -address