---
title: Ordering Context
---

classDiagram
    class Address {
        <<ValueObject>>
        -String street
        -String number
        -String complement
        -String neighborhood
        -String city
        -String state
        -ZipCode zipCode
    }

    class Product {
        <<ValueObject>>
        -ProductId id
        -ProductName name
        -Money price
        -Boolean inStock
        +checkOutOfStock()
    }

    namespace CustomerAggregate {
        class Customer {
            <<AggregateRoot>>
            -CustomerId id
            -FullName fullName
            -BirthDate birthDate
            -Email email
            -Phone phone
            -Document document
            -Boolean promotionNotificationsAllowed
            -Boolean archived
            -Instant registeredAt
            -Instant archivedAt
            -LoyaltyPoints loyaltyPoints
            +addLoyaltyPoints(LoyaltyPoints loyaltyPointsToAdd) void
            +archive() void
            +enablePromotionNotifications() void
            +disablePromotionNotifications() void
            +changeName(FullName newName) void
            +changeEmail(Email newEmail) void
            +changePhone(Phone newPhone) void
            +changeAddress(Address newAddress)
        }
    }
    Customer *-- Address: -address

    namespace OrderAggregate {
        class ShippingInfo {
            <<ValueObject>>
            -FullName fullName
            -Document document
            -Phone phone
        }

        class BillingInfo {
            <<ValueObject>>
            -FullName fullName
            -Document document
            -Phone phone
        }

        class OrderItem {
            <<Entity>>
            -OrderItemId id
            -ProductId productId
            -ProductName name
            -Money price
            -Quantity quantity
            -Money totalAmount
            ~ changeQuantity(Quantity newQuantity) void
        }

        class OrderStatus {
            <<enumeration>>
            DRAFT
            PLACED
            PAID
            READY
            CANCELED
        }

        class PaymentMethod {
            <<enumeration>>
            CREDIT_CARD
            GATEWAY_BALANCE
        }

        class Order {
            <<AggregateRoot>>
            -OrderId id
            -CustomerId id
            -Money totalAmount
            -Money shippingCost
            -Quantity totalItems
            -Instant placedAt
            -Instant paidAt
            -Instant canceledAt
            -Instant readyAt
            -LocalDate expectedDeliveryDate
            +markAsPaid() void
            +markAsReady() void
            +cancel() void
            +place() void
            +isPaid() boolean
            +isCanceled() boolean
            +isReady() boolean
            +isDraft() boolean
            +isPlaced() boolean
            +addItem(ProductId productId, ProductName productName, Money unitPrice, Quantity quantity) void
            +changePaymentMethod(PaymentMethod)
            +changeBilling(BillingInfo billingInfo) void
            +changeShipping(ShippingInfo shippingInfo, Money shippingCost, LocalDate expectedDeliveryDate) void
            +changeItemQuantity(OrderItemId, Quantity) void
            +removeItem(OrderItemId) void
        }
    }
    Order --> Customer
    Order *-- OrderStatus: -status
    Order *-- PaymentMethod: -paymentMethod
    Order *-- ShippingInfo: -shipping
    Order *-- BillingInfo: -billing
    Order "0..n" *-- OrderItem: -items
    ShippingInfo *-- Address: -address
    BillingInfo *-- Address: -address
    OrderItem --> Product