---
title: Ordering Context
---

classDiagram
    class Address {
        <<ValueObject>>
        -String street
        -String number
        -String complement
        -String neighborhood
        -String city
        -String state
        -ZipCode zipCode
    }

    class Product {
        <<ValueObject>>
        -ProductId id
        -ProductName name
        -Money price
        -Boolean inStock
        +checkOutOfStock() void
    }

    namespace CustomerAggregate {
        class Customer {
            <<AggregateRoot>>
            -CustomerId id
            -FullName fullName
            -BirthDate birthDate
            -Email email
            -Phone phone
            -Document document
            -Boolean promotionNotificationsAllowed
            -Boolean archived
            -Instant registeredAt
            -Instant archivedAt
            -LoyaltyPoints loyaltyPoints
            +addLoyaltyPoints(LoyaltyPoints) void
            +archive() void
            +enablePromotionNotifications() void
            +disablePromotionNotifications() void
            +changeName(FullName) void
            +changeEmail(Email) void
            +changePhone(Phone) void
            +changeAddress(Address) void
        }

        class CustomerRegisteredEvent {
            <<Event>>
            -CustomerId customerId
            -Instant registeredOn
        }

        class CustomerArchivedEvent {
            <<Event>>
            -CustomerId customerId
            -Instant archivedOn
        }
    }
    Customer *-- Address: -address
    Customer ..> CustomerRegisteredEvent: emit
    Customer ..> CustomerArchivedEvent: emit

    namespace OrderAggregate {
        class Recipient {
            <<ValueObject>>
            -FullName fullName
            -Document document
            -Phone phone
        }

        class Shipping {
            <<ValueObject>>
            -Money shippingCost
            -LocalDate expectedDeliveryDate
        }

        class Billing {
            <<ValueObject>>
            -FullName fullName
            -Document document
            -Phone phone
            -Email email
        }

        class OrderItem {
            <<Entity>>
            -OrderItemId id
            -ProductId productId
            -ProductName name
            -Money price
            -Quantity quantity
            -Money totalAmount
            ~ changeQuantity(Quantity) void
        }

        class OrderStatus {
            <<enumeration>>
            DRAFT
            PLACED
            PAID
            READY
            CANCELED
        }

        class PaymentMethod {
            <<enumeration>>
            CREDIT_CARD
            GATEWAY_BALANCE
        }

        class Order {
            <<AggregateRoot>>
            -OrderId id
            -CustomerId id
            -Money totalAmount
            -Quantity totalItems
            -Instant placedAt
            -Instant paidAt
            -Instant canceledAt
            -Instant readyAt
            +markAsPaid() void
            +markAsReady() void
            +cancel() void
            +place() void
            +isPaid() boolean
            +isCanceled() boolean
            +isReady() boolean
            +isDraft() boolean
            +isPlaced() boolean
            +addItem(Product, Quantity) void
            +changePaymentMethod(PaymentMethod) void
            +changeBilling(Billing) void
            +changeShipping(Shipping) void
            +changeItemQuantity(OrderItemId, Quantity) void
            +removeItem(OrderItemId) void
        }

        class OrderPlacedEvent {
            <<Event>>
            -OrderId orderId
            -CustomerId customerId
            -Instant placedOn
        }

        class OrderPaidEvent {
            <<Event>>
            -OrderId orderId
            -CustomerId customerId
            -Instant paidOn
        }

        class OrderReadyEvent {
            <<Event>>
            -OrderId orderId
            -CustomerId customerId
            -Instant readyOn
        }

        class OrderCanceledEvent {
            <<Event>>
            -OrderId orderId
            -CustomerId customerId
            -Instant canceledOn
        }
    }
    Order --> Customer
    Order *-- OrderStatus: -status
    Order *-- PaymentMethod: -paymentMethod
    Order *-- Shipping: -shipping
    Order *-- Billing: -billing
    Order *-- "0..n" OrderItem: -items
    Order ..> OrderPlacedEvent: emit
    Order ..> OrderPaidEvent: emit
    Order ..> OrderReadyEvent: emit
    Order ..> OrderCanceledEvent: emit
    Shipping *-- Address: -address
    Shipping *-- Recipient: -recipient
    Billing *-- Address: -address
    OrderItem --> Product

    namespace ShoppingCartAggregate {
        class ShoppingCart {
            <<AggregateRoot>>
            -ShoppingCartId id
            -CustomerId customerId
            -Money totalAmount
            -Quantity totalItems
            -Instant createdAt
            +startShopping(CustomerId)$ ShoppingCart
            +empty() void
            +addItem(Product, Quantity) void
            +removeItem(ShoppingCartItemId) void
            +refreshItem(Product) void
            +findItem(ShoppingCartItemId) ShoppingCartItem
            +findItem(ProductId) ShoppingCartItem
            +changeItemQuantity(ShoppingCartItemId, Quantity) void
            +containsUnavailableItems() boolean
            +isEmpty() boolean
        }

        class ShoppingCartItem {
            <<Entity>>
            -ShoppingCartItemId id
            -ShoppingCartId shoppingCartId
            -ProductId productId
            -ProductName productName
            -Money price
            -Quantity quantity
            -Money totalAmount
            -Boolean available
            ~ refresh(Product) void
            ~ changeQuantity(Quantity) void
        }

        class ShoppingCartCreatedEvent {
            <<Event>>
            -ShoppingCartId shoppingCartId
            -CustomerId customerId
            -Instant createdOn
        }

        class ShoppingCartItemAddedEvent {
            <<Event>>
            -ShoppingCartId shoppingCartId
            -CustomerId customerId
            -ProductId productId
            -Instant addedOn
        }

        class ShoppingCartItemRemovedEvent {
            <<Event>>
            -ShoppingCartId shoppingCartId
            -CustomerId customerId
            -ProductId productId
            -Instant removedOn
        }

        class ShoppingCartEmptiedEvent {
            <<Event>>
            -ShoppingCartId shoppingCartId
            -CustomerId customerId
            -Instant emptiedOn
        }
    }
    ShoppingCart *-- "0..n" ShoppingCartItem: items
    ShoppingCart --> Customer
    ShoppingCartItem --> Product
    ShoppingCart ..> ShoppingCartCreatedEvent: emit
    ShoppingCart ..> ShoppingCartItemAddedEvent: emit
    ShoppingCart ..> ShoppingCartItemRemovedEvent: emit
    ShoppingCart ..> ShoppingCartEmptiedEvent: emit