openapi: 3.0.1
info:
  title: AlgaShop - Ordering
  description: AlgaShop - Ordering
  version: 1.0.0
servers:
  - url: 'https://localhost:8080'
    description: Local Development Server
  - url: 'https://api.algashop.com'
    description: Production Server
paths:
  /api/v1/customers:
    post:
      summary: Register new customer
      description: Register new customer
      operationId: registerCustomer
      tags:
        - Customers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerInput'
      responses:
        201:
          description: Customer registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
          headers:
            Location:
              schema:
                type: string
                example: '/api/v1/customers/019b962e-cebd-7910-a5df-0afe586d05fe'
              description: URL of the newly created resource
        400:
          $ref: '#/components/responses/BadRequest'
        409:
          $ref: '#/components/responses/Conflict'
        422:
          $ref: '#/components/responses/UnprocessableEntity'
        500:
          $ref: '#/components/responses/InternalServerError'

    get:
      summary: Retrieve all customers
      description: Retrieve all customers
      operationId: getAllCustomers
      tags:
        - Customers
      parameters:
        - name: document
          in: query
          description: Document type to retrieve (optional)
          required: false
          schema:
            type: string
            example: '12345'
        - name: email
          in: query
          description: Email address to retrieve (optional)
          required: false
          schema:
            type: string
            format: email
            example: 'john.doe@example.com'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/size'
        - $ref: '#/components/parameters/sort'
        - $ref: '#/components/parameters/direction'
      responses:
        200:
          description: List of customers
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      content:
                        type: array
                        items:
                          $ref: '#/components/schemas/Customer'
                  - $ref: '#/components/schemas/Page'
        500:
          $ref: '#/components/responses/InternalServerError'

  /api/v1/customers/{customerId}:
    get:
      summary: Retrieve customer by ID
      description: Retrieve customer by ID
      operationId: getCustomerById
      tags:
        - Customers
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
            format: uuid
            example: '019b962e-cebd-7910-a5df-0afe586d05fe'
          description: ID of the customer to retrieve
      responses:
        200:
          description: Customer details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'

    put:
      summary: Update customer by ID
      description: Update customer by ID
      operationId: updateCustomerById
      tags:
        - Customers
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
            format: uuid
            example: '019b962e-cebd-7910-a5df-0afe586d05fe'
          description: ID of the customer to update
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerUpdateInput'
      responses:
        200:
          description: Customer updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        409:
          $ref: '#/components/responses/Conflict'
        500:
          $ref: '#/components/responses/InternalServerError'

    delete:
      summary: Delete customer by ID
      description: Delete customer by ID
      operationId: deleteCustomerById
      tags:
        - Customers
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
            format: uuid
            example: '019b962e-cebd-7910-a5df-0afe586d05fe'
          description: ID of the customer to delete
      responses:
        204:
          description: Customer deleted successfully
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'

components:
  parameters:
    page:
      name: page
      in: query
      description: Page number (optional)
      required: false
      schema:
        type: integer
        format: int32
        default: 0
    size:
      name: size
      in: query
      description: Page size (optional)
      required: false
      schema:
        type: integer
        format: int32
        default: 10
    sort:
      name: sortByProperty
      in: query
      description: Sorting criteria (optional)
      required: false
      schema:
        type: string
        example: 'firstName'
    direction:
      name: sortDirection
      in: query
      description: Sorting direction (optional)
      required: false
      schema:
        type: string
        enum: [ ASC, DESC ]
        default: ASC

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            BadRequest:
              $ref: '#/components/examples/BadRequest'
    Conflict:
      description: Conflict
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            Conflict:
              $ref: '#/components/examples/Conflict'
    InternalServerError:
      description: Internal server error
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            InternalServerError:
              $ref: '#/components/examples/InternalServerError'
    NotFound:
      description: Not Found
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            NotFound:
              $ref: '#/components/examples/NotFound'
    UnprocessableEntity:
      description: Unprocessable Entity
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            UnprocessableEntity:
              $ref: '#/components/examples/UnprocessableEntity'

  schemas:
    Customer:
      type: object
      required: [ 'id', 'firstName', 'lastName', 'email', 'document', 'phone', 'birthDate', 'loyaltyPoints', 'registeredAt', 'archivedAt', 'promotionNotificationsAllowed', 'archived', 'address' ]
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the customer
          example: '019b962e-cebd-7910-a5df-0afe586d05fe'
        firstName:
          type: string
          description: First name of the customer
          example: 'John'
        lastName:
          type: string
          description: Last name of the customer
          example: 'Doe'
        email:
          type: string
          format: email
          description: Email address of the customer
          example: 'john.doe@example.com'
        document:
          type: string
          description: Document associated with the customer
          example: '12345'
        phone:
          type: string
          description: Phone number of the customer
          example: '+1234567890'
        birthDate:
          type: string
          format: date
          description: Birth date of the customer
          example: '1980-01-01'
        loyaltyPoints:
          type: integer
          description: Number of loyalty points the customer has
          example: 1000
        registeredAt:
          type: string
          format: date-time
          description: Date and time when the customer was registered
          example: '2021-01-01T00:00:00.000Z'
        archivedAt:
          type: string
          format: date-time
          description: Date and time when the customer was archived
          nullable: true
        promotionNotificationsAllowed:
          type: boolean
          description: Indicates whether the customer wants to receive promotion notifications
          example: true
        archived:
          type: boolean
          description: Indicates whether the customer is archived
          example: false
        address:
          $ref: '#/components/schemas/Address'

    Address:
      type: object
      required: [ 'street', 'number', 'complement', 'neighborhood', 'city', 'state', 'zipCode' ]
      properties:
        street:
          type: string
          description: Street address
          example: '123 Main Street'
          nullable: false
          x-validation: [ 'notBlank' ]
        number:
          type: string
          description: House number or building name
          example: '123'
          nullable: false
          x-validation: [ 'notBlank' ]
        complement:
          type: string
          description: Additional information about the address
          example: 'Apt 4B'
          nullable: true
        neighborhood:
          type: string
          description: Neighborhood name
          example: 'Central Park'
          nullable: false
          x-validation: [ 'notBlank' ]
        city:
          type: string
          description: City name
          example: 'New York'
          nullable: false
          x-validation: [ 'notBlank' ]
        state:
          type: string
          description: State or province name
          example: 'NY'
          nullable: false
          x-validation: [ 'notBlank' ]
        zipCode:
          type: string
          description: Zip code
          example: '10001'
          nullable: false
          x-validation: [ 'notBlank' ]

    CustomerInput:
      type: object
      required: [ 'firstName', 'lastName', 'email', 'document', 'phone', 'birthDate', 'promotionNotificationsAllowed', 'address' ]
      properties:
        firstName:
          type: string
          description: First name of the customer
          example: 'John'
          nullable: false
          x-validation: [ 'notBlank' ]
        lastName:
          type: string
          description: Last name of the customer
          example: 'Doe'
          nullable: false
          x-validation: [ 'notBlank' ]
        email:
          type: string
          format: email
          description: Email address of the customer
          example: 'john.doe@example.com'
          nullable: false
          x-validation: [ 'notBlank', 'email' ]
        document:
          type: string
          description: Document associated with the customer
          example: '12345'
          nullable: false
          x-validation: [ 'notBlank' ]
        phone:
          type: string
          description: Phone number of the customer
          example: '+1234567890'
          nullable: false
          x-validation: [ 'notBlank' ]
        birthDate:
          type: string
          format: date
          description: Birth date of the customer
          example: '1980-01-01'
          nullable: false
          x-validation: [ 'pastDate' ]
        promotionNotificationsAllowed:
          type: boolean
          description: Indicates whether the customer wants to receive promotion notifications
          example: true
          nullable: false
        address:
          $ref: '#/components/schemas/Address'

    CustomerUpdateInput:
      type: object
      required: [ 'firstName', 'lastName', 'phone', 'promotionNotificationsAllowed', 'address' ]
      properties:
        firstName:
          type: string
          description: First name of the customer
          example: 'John'
          nullable: false
          x-validation: [ 'notBlank' ]
        lastName:
          type: string
          description: Last name of the customer
          example: 'Doe'
          nullable: false
          x-validation: [ 'notBlank' ]
        phone:
          type: string
          description: Phone number of the customer
          example: '+1234567890'
          nullable: false
          x-validation: [ 'notBlank' ]
        promotionNotificationsAllowed:
          type: boolean
          description: Indicates whether the customer wants to receive promotion notifications
          example: true
          nullable: false
        address:
          $ref: '#/components/schemas/Address'

    Error:
      type: object
      description: Error object returned by the API. Using RFC 9457 (Problem Details for HTTP APIs) standard.
      required: [ 'type', 'status', 'title', 'detail', 'instance' ]
      properties:
        type:
          type: string
          description: Error type
          example: 'https://httpstatuses.com/400'
        status:
          type: integer
          description: HTTP status code
          example: 400
        title:
          type: string
          description: Error title
          example: 'Bad Request'
        detail:
          type: string
          description: Error detail
          example: 'Invalid request parameters'
        instance:
          type: string
          description: Instance identifier
          example: '/api/customers'

    Page:
      type: object
      required: [ 'content', 'number', 'size', 'totalElements', 'totalPages' ]
      properties:
        number:
          type: integer
          description: Page number
          example: 0
        size:
          type: integer
          description: Page size
        totalElements:
          type: integer
          description: Total number of elements
          example: 100
        totalPages:
          type: integer
          description: Total number of pages
          example: 10

  examples:
    BadRequest:
      summary: Bad Request
      value:
        type: 'https://httpstatuses.com/400'
        status: 400
        title: 'Bad Request'
        detail: 'Invalid request parameters'
        instance: '/api/customers'
    Conflict:
      summary: Conflict
      value:
        type: 'https://httpstatuses.com/409'
        status: 409
        title: 'Conflict'
        detail: 'Resource conflict'
        instance: '/api/customers/123'
    InternalServerError:
      summary: Internal Server Error
      value:
        type: 'https://httpstatuses.com/500'
        status: 500
        title: 'Internal Server Error'
        detail: 'Internal server error'
        instance: '/api/customers/123'
    NotFound:
      summary: Not Found
      value:
        type: 'https://httpstatuses.com/404'
        status: 404
        title: 'Not Found'
        detail: 'Resource not found'
        instance: '/api/customers/123'
    UnprocessableEntity:
      summary: Unprocessable Entity
      value:
        type: 'https://httpstatuses.com/422'
        status: 422
        title: 'Unprocessable Entity'
        detail: 'Invalid request parameters'
        instance: '/api/customers/123'